---
# main tasks for rpi_get_temps role
- name: get cpu and gpu temps
  shell:
    cmd: |
      cpu=$(cat /sys/class/thermal/thermal_zone0/temp)
      echo "GPU=$(/opt/vc/bin/vcgencmd measure_temp | awk -F'(=)' '{print $2}')"
      echo "CPU=$((cpu/1000))'C"
      echo "$((cpu))"
  register: temps
  ignore_errors: true #will continue to run if a node is unreachable

- name: get poe fan level settings
  shell: cat /boot/config.txt | grep dtparam=poe | awk 'BEGIN { FS =  "="} ; {print $3}'
  register: speeds
  when: inc_fan_settings|bool
    
- name: cpu and gpu temps results
  debug:
    msg: "{{temps.stdout_lines[1]}} | {{temps.stdout_lines[0]}}" #alternate cpu var {{temps.stdout_lines[2]|int)/1000)|round|int}}

- name: poe fan temp level results
  debug:
    msg: "Fan levels: {{speeds.stdout_lines[0]}},{{speeds.stdout_lines[1]}},{{speeds.stdout_lines[2]}},{{speeds.stdout_lines[3]}}"
  when: inc_fan_settings|bool
